### PR TITLE
add gif

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging  show gif

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, [!all requests start with the magic word: Please](https://raw.githubusercontent.com/SteveL-MSFT/PoshChan-Bot/master/Assets/magicword.gif).

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging foo

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, all requests start with the magic word: Please.

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging test

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT,
all requests start with the magic word: Please.

**Pull request merged**
