### PR TITLE
Additional traces

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 1 minute ago

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 1 minute ago

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 1 minute ago

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 1 minute ago

**Pull request merged**
