### PR TITLE
Fix getting the name for PoshCan and also give error message when Please is not used

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Remind me in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, all requests start with the magic word Please.

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please remind me in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, will remind you in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 1 minute ago

**Pull request merged**
