### PR TITLE
use function instead of repeated push-outputbinding to send github response

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PSScriptAnalyzer

**Comment by PoshChan** [comment]
@SteveL-MSFT, did not find any matching pull request statuses

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild PSScriptAnalyzer

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find any matching pull request statuses

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild PSScriptAnalyzer

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, could not find build at: https://dev.azure.com/SteveL-MSFT/PoshChan-Bot/_apis/build/builds/4?api-version=5.0

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild PSScriptAnalyzer

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, could not find build at: https://dev.azure.com/SteveL-MSFT/PoshChan-Bot/_apis/build/builds/4?api-version=5.0, error: Invoke-RestMethod : Response status code does not indicate success: 401 (Unauthorized).\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:73 char:18\r\n+ ...    $build = Invoke-RestMethod -Uri $url -Authentication Basic -Creden ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: GET, Reques\\u2026PowerShell/6.2.0\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n \r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild PSScriptAnalyzer

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, successfully started rebuild of `PoshChan-PSScriptAnalyzer`

**Pull request merged**
