### PR TITLE
remove username from logging

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging please remind me in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, will remind you in 1 minute

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 1 minute ago

**Pull request merged**
