### PR TITLE
Fix path to build targets, added capability to set poshchan mention name to allow staging support

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please remind me in 1 minute

**Comment by SteveL-MSFT** [comment]
@PoshChan Please remind me in 5 minutes

**Comment by PoshChan** [comment]
@SteveL-MSFT, will remind you in 1 minute

**Comment by PoshChan** [comment]
@SteveL-MSFT, will remind you in 5 minutes

**Comment by PoshChan** [comment]
@SteveL-MSFT, this is the reminder you requested 1 minute ago

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please remind me in 2 minutes

**Comment by PoshChan** [comment]
@SteveL-MSFT, will remind you in 2 minutes

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, will remind you in 2 minutes

**Comment by PoshChan** [comment]
@SteveL-MSFT, this is the reminder you requested 5 minutes ago

**Comment by SteveL-MSFT** [comment]
@PoshChan Please remind me in 3 minutes

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 2 minutes ago

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please remind me in 4 minutes

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, will remind you in 4 minutes

**Comment by PoshChan** [comment]
@SteveL-MSFT, this is the reminder you requested 2 minutes ago

**Comment by PoshChan** [comment]
@SteveL-MSFT, will remind you in 3 minutes

**Comment by PoshChan** [comment]
@SteveL-MSFT, this is the reminder you requested 3 minutes ago

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 4 minutes ago

**Pull request merged**
