### PR TITLE
add support for AzDevOps retry

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please retry CI

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please retry CI

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start retry of `PoshChan-PSScriptAnalyzer`, error: Invoke-RestMethod : {\"$id\":\"1\",\"innerException\":null,\"message\":\"This request expects an object in the request body, but nothing was supplied.\",\"typeName\":\"Microsoft.TeamFoundation.Build.WebApi.RequestContentException, Microsoft.TeamFoundation.Build2.WebApi\",\"typeKey\":\"RequestContentException\",\"errorCode\":0,\"eventId\":3000}\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:127 char:25\r\n+                 $null = Invoke-RestMethod @params\r\n+                         ~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: PATCH, Requ\\u2026PowerShell/6.2.0\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please retry CI

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start retry of `PoshChan-PSScriptAnalyzer`, error: Invoke-RestMethod : {\"$id\":\"1\",\"innerException\":null,\"message\":\"This request expects an object in the request body, but the supplied data could not be deserialized.\",\"typeName\":\"Microsoft.TeamFoundation.Build.WebApi.RequestContentException, Microsoft.TeamFoundation.Build2.WebApi\",\"typeKey\":\"RequestContentException\",\"errorCode\":0,\"eventId\":3000}\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:138 char:25\r\n+                 $null = Invoke-RestMethod @params\r\n+                         ~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: PATCH, Requ\\u2026application/json\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please retry CI

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start retry of `PoshChan-PSScriptAnalyzer`, error: Invoke-RestMethod : {\"$id\":\"1\",\"innerException\":null,\"message\":\"This request expects an object in the request body, but the supplied data could not be deserialized.\",\"typeName\":\"Microsoft.TeamFoundation.Build.WebApi.RequestContentException, Microsoft.TeamFoundation.Build2.WebApi\",\"typeKey\":\"RequestContentException\",\"errorCode\":0,\"eventId\":3000}\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:139 char:25\r\n+                 $null = Invoke-RestMethod @params\r\n+                         ~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: PATCH, Requ\\u2026application/json\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please retry CI

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start retry of `PoshChan-PSScriptAnalyzer`, error: Invoke-RestMethod : {\"$id\":\"1\",\"innerException\":null,\"message\":\"Unable to retry pipeline 20190324.12 because the previous attempt did not fail.\",\"typeName\":\"Microsoft.TeamFoundation.Build.WebApi.BuildStatusInvalidChangeException, Microsoft.TeamFoundation.Build2.WebApi\",\"typeKey\":\"BuildStatusInvalidChangeException\",\"errorCode\":0,\"eventId\":3000}\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:139 char:25\r\n+                 $null = Invoke-RestMethod @params\r\n+                         ~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: PATCH, Requ\\u2026PowerShell/6.2.0\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n

**Pull request merged**
