### PR TITLE
Make 'please' word not mandatory any more

### PR DESCRIPTION
**Pull request by bergmeister**
I find it a bit annoying and a bot is not a human.

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Would it be better to make this configurable?

**Comment by bergmeister** [comment]
Let me ask this way:
If it was configurable, would you want to keep the setting turned on to keep the current behaviour for the PowerShell repos?

**Comment by SteveL-MSFT** [comment]
@bergmeister ok, how about this, just make `please` optional

**Comment by bergmeister** [comment]
Doesn't this PR's implementation already make `please` optional as one can put anything before the keyword due to it being a regex?
```pwsh
switch -Regex ("please get") { "get" { "Please was optional" } }
```

**Pull request merged**
