### PR TITLE
improve help message for unknown command

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging help me

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, all requests start with the magic word: Please

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging help

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, all requests start with the magic word: PleaseCommands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: ci
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: ci
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: ci
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: ci
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: ci

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging help

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, all requests start with the magic word: Please
Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    <value> is a number, and <units> can be minutes, hours, or days (singular or plural)
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    <value> is a number, and <units> can be minutes, hours, or days (singular or plural)
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    <value> is a number, and <units> can be minutes, hours, or days (singular or plural)
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    <value> is a number, and <units> can be minutes, hours, or days (singular or plural)
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    <value> is a number, and <units> can be minutes, hours, or days (singular or plural)
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    <value> is a number, and <units> can be minutes, hours, or days (singular or plural)
 Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    <value> is a number, and <units> can be minutes, hours, or days (singular or plural)

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging help

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, all requests start with the magic word: `Please`
Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for <target> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    <value> is a number, and <units> can be minutes, hours, or days (singular or plural)

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging help

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, all requests start with the magic word: `Please`
Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for \<target\> which can be a comma separated list are: `ci`
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    \<value\> is a number, and \<units\> can be minutes, hours, or days (singular or plural)

**Pull request merged**
