### PR TITLE
update readmex

### PR DESCRIPTION
**Pull request by SteveL-MSFT**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan rerun tests

**Comment by SteveL-MSFT** [comment]
@PoshChan hello

**Comment by SteveL-MSFT** [comment]
@PoshChan bye

**Comment by SteveL-MSFT** [comment]
@PoshChan hello

**Comment by PoshChan** [comment]
Authorized User: SteveL-MSFT
Command: hello
PR: https://api.github.com/repos/SteveL-MSFT/PoshChan-Bot/pulls/5

**Comment by SteveL-MSFT** [comment]
@PoshChan how are you

**Comment by PoshChan** [comment]
Authorized User: SteveL-MSFT
Command: how are you
PR: https://api.github.com/repos/SteveL-MSFT/PoshChan-Bot/pulls/5

**Comment by SteveL-MSFT** [comment]
@PoshChan can you see this?

**Comment by PoshChan** [comment]
Authorized User: SteveL-MSFT
Command: can you see this?
PR: https://api.github.com/repos/SteveL-MSFT/PoshChan-Bot/pulls/5

**Comment by SteveL-MSFT** [comment]
@PoshChan hello

**Comment by PoshChan** [comment]
Authorized User: SteveL-MSFT
Command: hello
PR: https://api.github.com/repos/SteveL-MSFT/PoshChan-Bot/pulls/5

**Comment by SteveL-MSFT** [comment]
@PoshChan hello world

**Comment by PoshChan** [comment]
Authorized User: SteveL-MSFT
Command: hello world
PR: https://api.github.com/repos/SteveL-MSFT/PoshChan-Bot/pulls/5

**Pull request merged**
